name: Visual Regression Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  chromatic-visual-tests:
    name: Chromatic Visual Regression
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Run Chromatic Visual Tests
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build-storybook'
          onlyChanged: true
          exitZeroOnChanges: true
          storybookBuildDir: 'storybook-static'
          autoAcceptChanges: ${{ github.ref == 'refs/heads/main' }}
          diagnostics: true
          junitReport: true
          skip: 'dependabot/**'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chromatic-test-results
          path: test-results/
          retention-days: 30

  cross-browser-tests:
    name: Cross-Browser Testing
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: npm run build-storybook

      - name: Start Storybook server
        run: |
          npx serve storybook-static -l 6006 &
          npx wait-on http://localhost:6006

      - name: Run Playwright cross-browser tests
        run: npm run test:cross-browser
        env:
          CI: true

      - name: Run Playwright visual tests (backup)
        run: npm run visual:local
        env:
          CI: true
        continue-on-error: true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload visual test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: visual-test-results
          path: visual-test-results/
          retention-days: 30

  performance-tests:
    name: Performance Testing
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run bundle analysis
        run: npm run test:bundle-size

      - name: Build for performance testing
        run: npm run build

      - name: Run performance tests
        run: npm run test:performance

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-results
          path: performance-results/
          retention-days: 30
