name: 🎯 Smart CI - Affected Packages Only

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect Changed Packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
      has_changes: ${{ steps.filter.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed packages
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            core:
              - 'packages/uswds-wc-core/**'
            actions:
              - 'packages/uswds-wc-actions/**'
            forms:
              - 'packages/uswds-wc-forms/**'
            navigation:
              - 'packages/uswds-wc-navigation/**'
            data-display:
              - 'packages/uswds-wc-data-display/**'
            feedback:
              - 'packages/uswds-wc-feedback/**'
            layout:
              - 'packages/uswds-wc-layout/**'
            structure:
              - 'packages/uswds-wc-structure/**'

      - name: Set has_changes flag
        id: set_flag
        run: |
          if [[ "${{ steps.filter.outputs.core }}" == "true" ]] || \
             [[ "${{ steps.filter.outputs.actions }}" == "true" ]] || \
             [[ "${{ steps.filter.outputs.forms }}" == "true" ]] || \
             [[ "${{ steps.filter.outputs.navigation }}" == "true" ]] || \
             [[ "${{ steps.filter.outputs.data-display }}" == "true" ]] || \
             [[ "${{ steps.filter.outputs.feedback }}" == "true" ]] || \
             [[ "${{ steps.filter.outputs.layout }}" == "true" ]] || \
             [[ "${{ steps.filter.outputs.structure }}" == "true" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

  smart-build:
    name: Build Affected Packages
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.has_changes == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.15.0'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: ppnpm install --frozen-lockfile

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Build affected packages
        run: |
          # Turborepo will only build changed packages + their dependents
          # Caching enabled via GitHub Actions cache above
          pnpm turbo build --filter="...[HEAD^]"

  smart-test:
    name: Test Affected Packages
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.has_changes == 'true'
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.15.0'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: ppnpm install --frozen-lockfile

      - name: Test ${{ matrix.package }}
        run: pnpm --filter "@uswds-wc/${{ matrix.package }}" test

  smart-lint:
    name: Lint Affected Packages
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.has_changes == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.15.0'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: ppnpm install --frozen-lockfile

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-lint-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-lint-
            ${{ runner.os }}-turbo-

      - name: Lint affected packages
        run: |
          pnpm turbo lint --filter="...[HEAD^]"

  all-checks-passed:
    name: ✅ All Checks Passed
    runs-on: ubuntu-latest
    needs: [changes, smart-build, smart-test, smart-lint]
    if: always()
    steps:
      - name: Check all jobs
        run: |
          if [[ "${{ needs.changes.outputs.has_changes }}" == "false" ]]; then
            echo "✅ No package changes detected - skipping CI"
            exit 0
          fi

          if [[ "${{ needs.smart-build.result }}" != "success" ]] || \
             [[ "${{ needs.smart-test.result }}" != "success" ]] || \
             [[ "${{ needs.smart-lint.result }}" != "success" ]]; then
            echo "❌ Some checks failed"
            exit 1
          fi

          echo "✅ All checks passed!"
